server:
  port: 8081

spring:
  application:
    name: user

hystrix:
  command:
    default:
      execution:
        isolation.thread.timeoutInMilliseconds: 3000

      circuitBreaker:
        requestVolumeThreshold: 1
        errorThresholdPercentage: 50