server:
  port: 8081

spring:
  application:
    name: user

hystrix:
  command:
    productInfo:
      default:
        execution:
          isolation.thread.timeoutInMilliseconds: 3000

        circuitBreaker:
          requestVolumeThreshold: 20
          errorThresholdPercentage: 50

product:
  ribbon:
    eureka:
      enabled: true
    #    listOfServers: localhost:8082
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
